version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user_DADN
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: db_DADN
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - env/.env

volumes:
  postgres_data: