"""Update device enum

Revision ID: 9585591d47bc
Revises: 
Create Date: 2025-03-24 23:37:55.539456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9585591d47bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE DeviceTypeEnum ADD VALUE 'camera';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    CREATE TYPE DeviceTypeEnum_old AS ENUM('temperature', 'humidity', 'light', 'sound');
    ALTER TABLE devices ALTER COLUMN name TYPE DeviceTypeEnum_old USING name::text::DeviceTypeEnum_old;
    DROP TYPE DeviceTypeEnum;
    ALTER TYPE DeviceTypeEnum_old RENAME TO DeviceTypeEnum;
    """)
    # ### end Alembic commands ###
